services:
  postgres:
    image: 'postgres:latest'
    container_name: "${CONTAINER_NAME}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5332:5432'
    volumes:
      - ./src/main/resources/sql:/home/sql
      - ./src/main/resources/scripts:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "log_statement=all" ]
