services:
  postgres:
    image: 'postgres:latest'
    container_name: "${CONTAINER_NAME}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - ${PORTS_MAPPING}
    volumes:
      - ${HOST_SQL_RESOURCES_PATH}:${CONTAINER_SQL_RESOURCE_PATH}
      - ${HOST_DB_REBUILD_SCRIPTS_PATH}:${CONTAINER_DB_REBUILD_SCRIPTS_PATH}
    command: [ "postgres", "-c", "log_statement=all" ]
