services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      LANG: "${LANG}"
      LC_ALL: "${LANG}"
    ports:
      - ${PORTS_MAPPING}
    volumes:
      - ${HOST_SQL_RESOURCES_PATH}:${CONTAINER_SQL_RESOURCE_PATH}
      - ${HOST_DB_REBUILD_SCRIPTS_PATH}:${CONTAINER_DB_REBUILD_SCRIPTS_PATH}
    command: [
      "postgres",
      "-c",
      "log_statement=all",
      "-c",
      "log_destination=stderr",
      "-c",
      "shared_preload_libraries=pg_cron",
      "-c",
      "cron.database_name=${POSTGRES_DB}",
    ]
